# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-19 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.folder


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('filer', '0007_auto_20161016_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlickCaroselImageFolder',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_slick_slickcaroselimagefolder', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('folder', filer.fields.folder.FilerFolderField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='filer.Folder')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='SlickCarousel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_slick_slickcarousel', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(blank=True, max_length=60, verbose_name='Title')),
                ('default_style', models.BooleanField(default=True, verbose_name='Use default style')),
                ('infinite', models.BooleanField(default=True, verbose_name='Infinite')),
                ('speed', models.IntegerField(default=300, verbose_name='Speed')),
                ('dots', models.BooleanField(default=True, verbose_name='Dots')),
                ('arrows', models.BooleanField(default=True, verbose_name='Arrows')),
                ('slides_to_show', models.IntegerField(default=1, verbose_name='Slides to show')),
                ('slides_to_scroll', models.IntegerField(default=1, verbose_name='Slides to scroll')),
                ('autoplay', models.BooleanField(default=False, verbose_name='Autoplay')),
                ('autoplay_speed', models.IntegerField(blank=True, null=True, verbose_name='Autoplay speed')),
                ('pause_on_hover', models.BooleanField(default=True, verbose_name='Pause on hover')),
                ('pause_on_dots_hover', models.BooleanField(default=False, verbose_name='Pause on dots hover')),
                ('fade', models.BooleanField(default=False, verbose_name='Fade animation')),
                ('center_mode', models.BooleanField(default=False, verbose_name='Center mode')),
                ('center_padding', models.CharField(blank=True, max_length=10, verbose_name='Center padding')),
                ('variable_width', models.BooleanField(default=False, verbose_name='Variable Width')),
                ('vertical', models.BooleanField(default=False, verbose_name='Vertical')),
                ('rigth_to_left', models.BooleanField(default=False, verbose_name='Right to left')),
                ('classes', models.TextField(blank=True, verbose_name='Css classes')),
            ],
            options={
                'verbose_name': 'Slick carousel',
                'verbose_name_plural': 'Slick carousels',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='SlickCarouselBreakpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakpoint', models.IntegerField(verbose_name='Breakpoint resolution')),
                ('slides_to_show', models.IntegerField(default=1, verbose_name='Slides to show')),
                ('slides_to_scroll', models.IntegerField(default=1, verbose_name='Slides to scroll')),
                ('carousel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakpoints', to='cmsplugin_slick.SlickCarousel', verbose_name='Slick carousel')),
            ],
        ),
        migrations.CreateModel(
            name='SlickCarouselElementWrapper',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_slick_slickcarouselelementwrapper', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('classes', models.TextField(blank=True, verbose_name='Css classes')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
