# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-20 01:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.folder


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('filer', '0007_auto_20161016_1055'),
        ('cmsplugin_slick', '0005_carousel_height'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CaroselImageFolder',
            new_name='SlickCarouselImageFolder',
        ),
        migrations.RenameModel(
            old_name='Carousel',
            new_name='SlickCarousel',
        ),
        migrations.RenameModel(
            old_name='CarouselElementWrapper',
            new_name='SlickCarouselWrappedSlide',
        ),
        migrations.RenameModel(
            old_name='CarouselBreakpoint',
            new_name='SlickCarouselBreakpoint',
        ),
        migrations.RunSQL([("UPDATE cms_cmsplugin SET plugin_type = REPLACE(plugin_type, 'CarouselPlugin', 'SlickCarouselPlugin');", None)]),
        migrations.RunSQL([("UPDATE cms_cmsplugin SET plugin_type = REPLACE(plugin_type, 'CarouselElementWrapperPlugin', 'SlickCarouselWrappedSlidePlugin');", None)]),
        migrations.RunSQL([("UPDATE cms_cmsplugin SET plugin_type = REPLACE(plugin_type, 'CarouselImageFolderPlugin', 'SlickCarouselImageFolderPlugin');", None)]),
        migrations.AddField(
            model_name='slickcarouselwrappedslide',
            name='title',
            field=models.CharField(verbose_name='Title', blank=True, max_length=255),
        ),
    ]
