# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-20 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_slick', '0006_refactoring_and_merge_paramono'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slickcarousel',
            options={'verbose_name': 'Slick Carousel', 'verbose_name_plural': 'Slick Carousels'},
        ),
        migrations.AlterModelOptions(
            name='slickcarouselbreakpoint',
            options={'verbose_name': 'Carousel Breakpoint', 'verbose_name_plural': 'Carousels Breakpoints'},
        ),
        migrations.AlterModelOptions(
            name='slickcarouselimagefolder',
            options={'verbose_name': 'Carousel Image Folder', 'verbose_name_plural': 'Carousels Image Folders'},
        ),
        migrations.AlterModelOptions(
            name='slickcarouselwrappedslide',
            options={'verbose_name': 'Wrapped Slide', 'verbose_name_plural': 'Wrapped Slides'},
        ),
        migrations.RemoveField(
            model_name='slickcarousel',
            name='height',
        ),
        migrations.AddField(
            model_name='slickcarousel',
            name='adaptive_height',
            field=models.BooleanField(default=False, verbose_name='Adaptive Height'),
        ),
        migrations.AddField(
            model_name='slickcarousel',
            name='rows',
            field=models.PositiveIntegerField(default=1, verbose_name='Rows'),
        ),
        migrations.AddField(
            model_name='slickcarousel',
            name='slides_per_row',
            field=models.PositiveIntegerField(default=1, verbose_name='Slides per row'),
        ),
        migrations.AlterField(
            model_name='slickcarousel',
            name='classes',
            field=models.TextField(blank=True, verbose_name='CSS classes'),
        ),
        migrations.AlterField(
            model_name='slickcarousel',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_slick_slickcarousel', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='slickcarouselimagefolder',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_slick_slickcarouselimagefolder', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='slickcarouselwrappedslide',
            name='classes',
            field=models.TextField(blank=True, verbose_name='CSS classes'),
        ),
        migrations.AlterField(
            model_name='slickcarouselwrappedslide',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_slick_slickcarouselwrappedslide', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='slickcarouselwrappedslide',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
    ]
